[package]
name = "peida_blog"
version = "0.1.0"
authors = ["p31d4"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.8.9"
dioxus = { version = "0.7.1", features = ["ssr"] }
dioxus-ssr = "0.7.9"
tokio = { version = "1.52.3", features = ["full"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
